config/routes.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Cotopaxi::Application.routes.draw do
  devise_for :users

  resources :users

  resources :projects do
    resources :features
    resources :sprints
  end

  post 'projects/:id/sort_features' => 'projects#sort_features', format: :json
  post 'projects/:id/assign_roles' => 'projects#assign_roles'
  put  'projects/:id/assign_roles' => 'projects#assign_roles'
  patch 'projects/:id/assign_roles' => 'projects#assign_roles'
  get 'projects/:id/plan_sprint' => 'projects#plan_sprint'
  post 'projects/:id/confirm_sprint' => 'projects#confirm_sprint', format: :json
  get 'projects/:id/past_sprints' => 'sprints#past_sprints'

  root to: "users#show"

end

app/models/user.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :nickname, :email
  validates_uniqueness_of :nickname, :email
  has_many :roles, dependent: :destroy
  has_many :projects, through: :roles
end

app/controllers/users_controller.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
class UsersController < ApplicationController

  load_and_authorize_resource

  def current_ability
    @current_ability ||= Ability.new(current_user, 0)
  end

  # GET /users
  # GET /users.json
  def index
    authorize! :manage, :all
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if params[:id].nil?
      @user = current_user
      if @user.projects.count == 1
        redirect_to @user.projects[0] and return
      end
    else
      @user = User.find(params[:id])
      if @user.projects.count == 1 and current_user.nickname != 'AdM'
        redirect_to @user.projects[0] and return
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :nickname, :stakeholder)
  end
end

app/views/users/_form.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
= form_for @user, html: {class: "form-horizontal"} do |f|
  - if @user.errors.any?
    .container
      .alert.alert-danger
        %h6= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg

  %div{class: "control-group"}
    = f.label :email, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-envelope"}
        = f.text_field :email
  %div{class: "control-group"}
    = f.label :first_name, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :first_name
  %div{class: "control-group"}
    = f.label :last_name, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :last_name
  %div{class: "control-group"}
    = f.label :nickname, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-user"}
        = f.text_field :nickname
  %div{class: "control-group"}
    = f.label :password, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-lock"}
        = f.password_field :password
  %div{class: "control-group"}
    = f.label :password_confirmation, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-lock"}
        = f.password_field :password_confirmation
  %div{class: "control-group"}
    %div{class: "controls"}
      = f.submit class: "btn"

app/views/users/edit.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend Edit user details

= render 'form'
= link_to 'Back', user_path(@user), class: 'btn btn-success', type:'button'

app/views/users/index.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend Users:

%table{class: "table table-hover"}
  %thead
    %tr
      %th Email
      %th First name
      %th Last name
      %th Nickname
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.first_name
        %td= user.last_name
        %td= user.nickname
        %td= link_to 'Show', user, class: 'btn btn-small', type:'button'
        -if can? :manage, user
          %td= link_to 'Edit', edit_user_path(user), class: 'btn btn-small btn-warning', type:'button'
          %td= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger', type:'button'

%br

= link_to 'New User', new_user_path, class: 'btn btn-primary', type:'button'
= link_to 'Back', projects_path, class: 'btn btn-success', type:'button'

app/views/users/new.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend New user

= render 'form'

= link_to 'Back', users_path, class: 'btn btn-success', type:'button'

app/views/users/show.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend #{if can? :manage, :all; @user.nickname+"'s" else "Your" end} Projects

%table{class: "table table-hover"}
  %thead
    %tr
      %th Name
      %th Description
      %th State
    -@user.projects.uniq.each do |project|
      %tr{class: project.set_title_background}
        %td= project.name
        %td= project.description
        %td
          %span{class: "label label-#{project.set_status_label}"}
            = project.state.humanize
        %td= link_to 'View Details', project, class: 'btn btn-small', type:'button'
        -#%td= link_to 'Delete', project, class: 'btn btn-danger btn-small', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
        -#%td= link_to "#{project.set_state_change_button}", url_for(controller: :projects, action: :update, id: project.id, project: { state_event: project.set_state_transition }), class: "btn btn-small #{project.set_disabled_button} tBTN", type:'button', method: :put

-if can? :manage, :all
  = link_to 'New Project', new_project_path, class: 'btn btn-primary', type:'button'