config/routes.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Cotopaxi::Application.routes.draw do
  devise_for :users

  resources :users

  resources :projects do
    resources :features
    resources :sprints
  end

  post 'projects/:id/sort_features' => 'projects#sort_features', format: :json
  post 'projects/:id/assign_roles' => 'projects#assign_roles'
  put  'projects/:id/assign_roles' => 'projects#assign_roles'
  patch 'projects/:id/assign_roles' => 'projects#assign_roles'
  get 'projects/:id/plan_sprint' => 'projects#plan_sprint'
  post 'projects/:id/confirm_sprint' => 'projects#confirm_sprint', format: :json
  get 'projects/:id/past_sprints' => 'sprints#past_sprints'

  root to: "users#show"

end

app/models/project.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
class Project < ActiveRecord::Base
  has_many :features, dependent: :destroy
  has_many :sprints, dependent: :destroy
  validates_presence_of :description, :name
  has_many :roles, dependent: :destroy
  has_many :users, through: :roles

  has_many :team_member_roles, -> { where role: 'team_member' }, class_name: Role.name
  has_many :team_members, through: :team_member_roles, source: :user

  has_many :stakeholder_roles, -> {where role: 'stakeholder' }, class_name: Role.name
  has_many :stakeholders, through: :stakeholder_roles, source: :user

  has_many :customer_roles, -> { where role: 'customer' }, class_name: Role.name
  has_many :customers, through: :customer_roles, source: :user

  has_one :scrum_master_role, -> {where role: 'scrum_master' }, class_name: Role.name
  has_one :scrum_master, through: :scrum_master_role, source: :user

  has_one :product_owner_role, -> { where role: 'product_owner' }, class_name: Role.name
  has_one :product_owner, through: :product_owner_role, source: :user


  SINGLE_ROLES = [:scrum_master, :product_owner]
  MANY_ROLES = [:customers, :stakeholders, :team_members]

  state_machine :state, initial: :created do
    #before_transition on:  :complete, do: :features_done?

    event :start do
      transition :created => :in_progress
    end

    event :complete do
      transition :in_progress => :done
    end
  end

  def project_ability(user)
    current_ability = Ability.new(user, self.id)
  end

  def features_done?
    counter = 0
    self.features.each do |feature|
      if feature.state == 'done'
          counter += 1
      end
    end
    if counter == features.length
      true
    else
      false
    end
  end

  def set_title_background
    status = {'created' => 'info', 'in_progress' => 'warning', 'done' => 'success'}
    status[self.state]
  end

  def set_state_change_button
    status = {'created' => 'Start!', 'in_progress' => 'Complete!', 'done' => 'Done!'}
    status[self.state]
  end

  def set_state_transition
    trans = {'created' => :start, 'in_progress' => :complete, 'done' => :done}
    trans[self.state]
  end

  def set_disabled_button
    status = {'created' => 'btn-success','in_progress' => self.complete_button, 'done' => 'disabled'}
    status[self.state]
  end

  def set_status_label
    status = {'created' => 'info', 'in_progress' => 'important', 'done' => 'success'}
    status[self.state]
  end

  def complete_button
    if self.features_done?
      'btn-success'
    else
      'btn-danger prevent'
    end
  end

  def drag_available
    if self.features_done?
      "no_drag"
    else
      "feature_table"
    end
  end

  def disable_new_feature
    if self.state == 'done'
      'disabled'
    else
      'btn-primary'
    end
  end

  def get_unassigned_features
    un_ass = []
    self.features.each do |feature|
      if feature.sprint.nil?
        un_ass << feature
      end
    end
    un_ass
  end

  def assign_roles(params)
    @role_to_be = Role.find(params[:id])
    @role_to_be.update_attributes(params)
  end

  def next_sprint_text
    if self.sprints.last
      case self.sprints.last.state
        when 'done'
          'Plan Next Sprint'
        when 'in_progress'
          'Review  Current Sprint'
        when 'created'
          'Review  Current Sprint'
        else
          'Plan Sprint'
      end
    else
      'Plan Sprint'
    end

  end
end

app/controllers/projects_controller.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
class ProjectsController < ApplicationController

  def current_ability
    @current_ability ||= Ability.new(current_user, params[:id])
  end

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @features = @project.features.by_priority
    @users = User.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    authorize! :create, Project
    @project = Project.new
    #authorize! :create, @project

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    authorize! :edit, Project
    @project = Project.find(params[:id])
    @users = User.all
  end

  # POST /projects
  # POST /projects.json
  def create
    authorize! :create, Project
    @project = Project.new(project_params)
    @project.roles << Role.new(role: :product_owner, project_id: @project.id)
    @project.roles << Role.new(role: :scrum_master, project_id: @project.id)
    @project.stakeholder_ids = current_user.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, flash: {success: 'Project was successfully created.'}}
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    authorize! :update, Project
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to @project, flash: {success: 'Project was successfully updated.'}}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize! :destroy, Project
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, flash: {success: 'Project was successfully deleted.'} }
      format.json { head :no_content }
    end
  end

  def sort_features
    authorize! :prioritize_feature, Project
    @project = Project.find(params[:id])
    @order = params[:order]
    @index = 1
    @order.each do |order|
      feature = @project.features.find(order)
      feature.priority = @index
      feature.save!
      @index += 1
    end
    respond_to do |format|
      format.json { render json: @order }
      format.html
    end

  end

  def assign_roles
    new_params = params[:role]
    authorize! :assign_roles, Project
    @project = Project.find(params[:id])
    @project.assign_roles(role_params(new_params))
    respond_to do |format|
      format.html { redirect_to project_url(@project), flash: {success: 'Project was successfully updated.'} }
      format.json { render json: @project }
    end

  end

  def plan_sprint
    @project = Project.find(params[:id])
    if @project.sprints == []
      @sprint = Sprint.new
      @sprint.duration = @project.sprint_duration
      @sprint.project = @project
      @sprint.save!
    elsif @project.sprints.last.state == 'done'
      index = @project.sprints.last.number
      index += 1
      @sprint = Sprint.new
      @sprint.duration = @project.sprint_duration
      @sprint.project = @project
      @sprint.number = index
      @sprint.save!
    else
      @sprint = @project.sprints.last
    end

    respond_to do |format|
      format.html
    end
  end

  def confirm_sprint
    @feature = Feature.find(params[:feature_id])
    if params[:sprint_id] != "0"
      @sprint = Sprint.find(params[:sprint_id])
      @feature.sprint = @sprint
    else
      @feature.sprint = nil
    end

    respond_to do |format|
      if @feature.save
        format.json {render json: @sprint}
        format.html
      else
        format.json {render json: @sprint.errors, status: :unprocessable_entity}
        format.html
      end

    end
  end

  private
  # Only allow a trusted parameter "white list" through.
  def project_params
    params.require(:project).permit(:description, :name, :state, :state_event, :sprint_duration, customer_ids: [], stakeholder_ids: [], team_member_ids: [] )
  end

  def role_params(par)
    par.permit(:project_id, :role, :id, :user_id)
  end
end

app/views/projects/_assign_message.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
.container.show{style: "display: none; width: 100%;"}
  .alert.alert-success Roles have been successfully assigned!

.container.showError{style: "display: none; width: 100%;"}
  .alert.alert-danger You don't have permission to change the roles!


-if can? :assign_roles, Project
  .container.hide4{style: "width: 100%;"}
    .alert.alert-success Roles have already been assigned. You can edit them below:

.progress.progress-striped.active{style: "display: none;", id: "loader"}
  .bar{style: "width: 0%;"}

app/views/projects/_drop_zone.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%li
  .cubic.noSort
    %h6{class: "popover-title"}
      Drop items here.
      %i{class: "icon-arrow-right"}

app/views/projects/_edit_roles.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
#manyForms
  -product_owner = @project.roles.find_by_role('product_owner')
  = semantic_form_for(product_owner, url: "/projects/#{@project.id}/assign_roles.json", html: {class: "form-horizontal", id: "product_owner_form", autocomplete: "off"}) do |f|
    =f.hidden_field :project_id, value: @project.id
    =f.hidden_field :role, value: product_owner.role
    =f.hidden_field :id, value: product_owner.id
    = f.input :user_id, as: :select, collection: Hash[@users.map{ |user| [user.nickname, user.id]}], label: "Product Owner", :input_html => {id: "assignChz"}

  -scrum_master = @project.roles.find_by_role('scrum_master')
  = semantic_form_for(scrum_master, url: "/projects/#{@project.id}/assign_roles.json", html: {class: "form-horizontal", id: "scrum_master_form", autocomplete: "off"}) do |fs|
    =fs.hidden_field :project_id, value: @project.id
    =fs.hidden_field :role, value: scrum_master.role
    =fs.hidden_field :id, value: scrum_master.id
    =fs.input :user_id, as: :select, collection: Hash[@users.map{ |user| [user.nickname, user.id]}], label: "Scrum Master", :input_html => {class: "chzn-select"}

  = semantic_form_for(@project, html: {class: "form-horizontal", id: "multiple-form", autocomplete: "off"}) do |fd|
    -Project::MANY_ROLES.each do |role_name|
      =fd.input role_name, as: :select, member_label: :nickname, :input_html => {class: "chzn-select"}

app/views/projects/_form.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
= form_for(@project, html: {class: "form-horizontal"}) do |f|
  - if @project.errors.any?
    %div{id: "error_explanation"}
      %h2= pluralize(@project.errors.count, "error"); " prohibited this project from being saved:"
      %ul
        -@project.errors.full_messages.each do |msg|
          %li= msg

  %div{class: "control-group"}
    = f.label :name, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :name
  %div{class: "control-group"}
    = f.label :description, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-tasks"}
        = f.text_area :description, rows: 8
  %div{class: "control-group"}
    = f.label :sprint_duration, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-calendar"}
        = f.select :sprint_duration, [["1 Week", 604800], ["2 Weeks", 1209600], ["3 Weeks", 1814400], ["4 Weeks", 2419200]]
  %div{class: "control-group"}
    %div{class: "controls"}
      = f.submit class: "btn"

app/views/projects/_roles.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
.modal.hide.fade{id: "assign_modal", backdrop: "static"}
  .modal-header
    %button{type: "button", class: "close modalClose", "data-dismiss"=>"modal", "aria-hidden" => "true"}x
    %h5{id: "editable"}= if can? :assign_roles, Project; "Assign roles for project:" else "Team:" end
  .modal-body
    =render 'assign_message'
    =render 'edit_roles'
    -if can? :assign_roles, Project
      %button{class: "btn btn-warning", id: "multiRoleAssign"}Assign Roles
    -else
      %button{class: "btn disabled"}Assign Roles
  .modal-footer
    %button{class: "btn modalClose", "data-dismiss"=>"modal", "aria-hidden" => "true"}Close

app/views/projects/edit.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend Edit Project: #{@project.name}

= render 'form'
= link_to 'Back', project_path(@project), class: 'btn btn-success', type:'button'

app/views/projects/index.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend{id: 'home'} Current Projects

%table{class: "table table-hover"}
  %thead
    %tr
      %th Name
      %th Description
      %th State
    - @projects.each do |project|
      %tr{class: project.set_title_background}
        %td= project.name
        %td= project.description
        %td
          %span{class: "label label-#{project.set_status_label}"}
            = project.state.humanize
        %td= link_to 'View Details', project, class: 'btn btn-small', type:'button'
-#        -if project.project_ability(current_user).can? :manage, project
-#          %td= link_to 'Delete', project, class: 'btn btn-danger btn-small', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
-#          %td= link_to "#{project.set_state_change_button}", url_for(controller: :projects, action: :update, id: project.id, project: { state_event: project.set_state_transition }), class: "btn btn-small #{project.set_disabled_button} tBTN", type:'button', method: :put

-if can? :manage, Project
  = link_to 'New Project', new_project_path, class: 'btn btn-primary', type:'button'

app/views/projects/new.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend New project

= render 'form'

= link_to 'Back', projects_path, class: 'btn btn-success', type:'button'

app/views/projects/plan_sprint.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend{id: "project_id", name: @project.id}
  Plan sprint for project: #{@project.name}
  %small Sprint number: #{@sprint.number}
  %span{class: "label label-#{@sprint.set_status_label}"}
    =@sprint.state.humanize
  -if @sprint.finish_date
    -if Time.now < @sprint.finish_date
      %br/
      %small Sprint ends on #{@sprint.finish_date}
    -else
      %br/
      %small Sprint ended on #{@sprint.finish_date}



.row
  .span6
    %h5 Product backlog:
    %ul#backDropZone{style: "list-style-type: none;", name: @sprint.id}
      = render 'drop_zone'
      -@project.features.by_priority.each do |feature|
        -if feature.sprint.nil? #_id != @sprint.id
          %li
            .cubic.draggable{id: feature.id, name: 'droppedL'}
              %h3{class: "popover-title"}= feature.name
              .popover-content
                %p= feature.description

  .span6
    %h5 Current Sprint backlog:
    %ul#dropZone{style: "list-style-type: none;", name: @sprint.id}
      = render 'drop_zone'
      -@sprint.features.by_priority.each do |feature|
        %li
          .cubic.draggable{id: feature.id, name: 'droppedR'}
            %h3{class: "popover-title"}= feature.name
            .popover-content
              %p= feature.description

%br/
= link_to 'Back', project_path(@project), class: 'btn', type:'button'
= link_to "#{@sprint.set_state_change_button}", url_for(controller: :sprints, action: :update, project_id: @project.id, id: @sprint.id, sprint: { state_event: @sprint.set_state_transition }), class: "btn btn-success", type:'button', method: :put

app/views/projects/show.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend= @project.name

%table{class: "table table-bordered"}
  %tr{class: @project.set_title_background}
    %td= @project.description
    %td{style: "text-align: center"}
      %button{class: "btn", id: "modalShow"}
        -if can? :assign_roles, @project
          Assign Roles
        -else
          View Team
    %td{style: "text-align: center"}
      %span{class: "label label-#{@project.set_status_label}"}
        = @project.state.humanize
    -if can? :update, @project
      %td{style: "text-align: center"}= link_to 'Delete', @project, id: "deleteP", class: 'btn btn-danger btn-small', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
      %td{style: "text-align: center"}= link_to "#{@project.set_state_change_button}", url_for(controller: :projects, action: :update, id: @project.id, project: { state_event: @project.set_state_transition }), id: "projectState", class: "btn btn-small #{@project.set_disabled_button} tBTN", type:'button', method: :put



-if @project.users.count == 1
  .container#assignAlert
    .alert.alert-danger
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      You haven't assigned any roles to the members of this project. Please do so now.


-if @project.features.any?
  = render "features/feature"
-else
  %span
    -if can? :create, Feature
      = link_to 'Add Features', new_project_feature_path(@project), class: 'btn btn-primary', type:'button'

= render 'roles'
-if can? :prioritize_feature, Project and not @project.features_done? #and @project.get_unassigned_features.count != 0
  = link_to @project.next_sprint_text, "/projects/#{@project.id}/plan_sprint", class: 'btn btn-warning', type:'button'
-if can? :update, Project
  = link_to 'Edit Project', edit_project_path(@project), class: 'btn btn-warning', type:'button'

-if current_user.projects.count != 1
  = link_to 'Back', current_user, class: 'btn', type:'button'