config/routes.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

Cotopaxi::Application.routes.draw do
  devise_for :users

  resources :users

  resources :projects do
    resources :features
    resources :sprints
  end

  post 'projects/:id/sort_features' => 'projects#sort_features', format: :json
  post 'projects/:id/assign_roles' => 'projects#assign_roles'
  put  'projects/:id/assign_roles' => 'projects#assign_roles'
  patch 'projects/:id/assign_roles' => 'projects#assign_roles'
  get 'projects/:id/plan_sprint' => 'projects#plan_sprint'
  post 'projects/:id/confirm_sprint' => 'projects#confirm_sprint', format: :json
  get 'projects/:id/past_sprints' => 'sprints#past_sprints'

  root to: "users#show"

end

app/models/feature.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
class Feature < ActiveRecord::Base
  belongs_to :project
  belongs_to :sprint
  validates_presence_of :project, :name, :description
  scope :by_priority, -> { order('priority asc') }

  before_create :set_priority

  state_machine :state, initial: :created do
    after_transition on:  :start, do: :start_project

    event :start do
      transition :created => :in_progress
    end

    #event :assign do
      #transition :started => :in_progress
    #end

    event :complete do
      transition :in_progress => :done
    end
  end

  def get_difficulty
    dif = {1 => 'Very easy', 2 => 'Easy', 3 => 'Medium', 4 => 'Hard', 5 => 'Really Hard', 6 => 'Almost Impossible'}
    dif[self.difficulty] + " (#{self.difficulty})"
  end

  def set_status_label
    status = {'created' => 'info', 'started' => 'inverse', 'in_progress' => 'important', 'done' => 'success'}
    status[self.state]
  end

  def set_priority
    if self.project.features.by_priority.last
      self.priority = self.project.features.by_priority.last.priority
      self.priority += 1
    else
      self.priority = 1
    end
  end

  def set_state_change_button
    status = {'created' => 'Start!', 'in_progress' => 'Complete!', 'done' => 'Done!'}
    status[self.state]
  end

  def set_state_transition
    trans = {'created' => :start, 'in_progress' => :complete, 'done' => :done}
    trans[self.state]
  end

  def set_disabled_button
    if self.project.state == 'done'
      'disabled'
    else
      status = {'created' => 'btn-success', 'started' => 'btn-info', 'in_progress' => 'btn-success', 'done' => 'disabled'}
      status[self.state]
    end
  end

  def start_project
    if self.project.state == 'created'
      self.project.state = 'in_progress'
      self.project.save!
    end
  end
end

app/controllers/features_controller.rb
# Cotopaxi | Scrum Management Tool
# Copyright (C) 2012  MHM-Systemhaus GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>..
class FeaturesController < ApplicationController

  load_and_authorize_resource

  def current_ability
    @current_ability ||= Ability.new(current_user, params[:project_id])
  end
  # GET /features
  # GET /features.json
  def index
    @project = Project.find(params[:project_id])
    @features = @project.features.by_priority

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @feature = Feature.new
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = Feature.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)
    @project = Project.find(params[:project_id])
    @feature.project = @project

    respond_to do |format|
      if @feature.save
        format.html { redirect_to project_url(@feature.project), flash: {success: 'Feature was successfully created.'}}
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(feature_params)
        format.html { redirect_to project_url(@feature.project), flash: {success: 'Feature was successfully updated.'}}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = Feature.find(params[:id])
    project = @feature.project
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to project_url(project), flash: {success: 'Feature was successfully deleted.'} }
      format.json { head :no_content }
    end
  end

  private
  # Only allow a trusted parameter "white list" through.
  def feature_params
    params.require(:feature).permit(:description, :name, :state, :difficulty, :priority, :state_event, :project_id, :sprint_id)
  end
end

app/views/features/_feature.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%h5 #{@project.name}'s current features
%hr/
-if @project.sprints == []
  .container
    .alert.alert-danger
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      No sprint has been planned yet!

.alert.alert-success.notice{style: "display: none;", id: "sorted"}
.alert.alert-danger.notice{style: "display: none;", id: "errorSort"}
%img{style: "display: none;", id: "loadingImage", src: "/img/ajax-loader.gif"}

= render 'features/tab_navbar'

.tab-content
  = render 'features/tab_all'
  = render 'features/tab_current_sprint'
  = render 'features/tab_no_sprint'
  .tab-pane#pastSprints

app/views/features/_form.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
= form_for([@project, @feature], html: {class: "form-horizontal"}) do |f|
  - if @feature.errors.any?
    #error_explanation
      %h2
        = pluralize(@feature.errors.count, "error")
        prohibited this feature from being saved:
      %ul
        - @feature.errors.full_messages.each do |msg|
          %li= msg

  %div{class: "control-group"}
    = f.label :name, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :name
  %div{class: "control-group"}
    = f.label :description, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-tasks"}
        = f.text_area :description, rows: 8
  %div{class: "control-group"}
    = f.label :difficulty, class: "control-label"
    %div{class: "controls"}
      %div{class: "input-prepend"}
        %span{class: "add-on"}
          %i{class: "icon-exclamation-sign"}
        = f.select :difficulty, [['Very easy', 1], ['Easy', 2], ['Medium', 3], ['Hard', 4], ['Really Hard', 5], ['Almost Impossible', 6]]
  %div{class: "control-group"}
    %div{class: "controls"}
      = f.submit class: "btn"

app/views/features/_tab_all.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
.tab-pane#allFeatures{class: unless @project.sprints.last; 'active' end}
  %table{class: "table table-hover #{if can? :prioritize_feature, @project; @project.drag_available else "no_drag" end}", name: @project.id}
    %thead
      %tr
        %th Name
        %th Description
        %th Status
        %th Difficulty
    - @features.each do |feature|
      %tr{id: feature.id}
        %td= feature.name
        %td= feature.description
        %td
          %span{class: "label label-#{feature.set_status_label}"}
            = feature.state.humanize
        %td= feature.difficulty
        -#%td= link_to 'Show', [@project, feature], class: 'btn btn-small', type:'button'
        -if can? :manage, Feature
          %td= link_to 'Edit', edit_project_feature_path(@project, feature), class: 'btn btn-warning btn-small', type:'button'
          %td= link_to 'Delete', project_feature_path(@project, feature), class: 'btn btn-danger btn-small', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
          %td= link_to "#{feature.set_state_change_button}", url_for(controller: :features, action: :update, project_id: @project.id, id: feature.id, feature: { state_event: feature.set_state_transition }), class: "btn btn-small #{feature.set_disabled_button} tBTN", type:'button', method: :put

  -if can? :create, Feature
    = link_to 'New Feature', new_project_feature_path(@project), class: "btn #{@project.disable_new_feature}", type:'button'
    %br/
    %br/

app/views/features/_tab_current_sprint.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
-if @project.sprints.last
  .tab-pane.active#currentSprint
    .alert.alert-info
      -#%button.close{"data-dismiss" => "alert", :type => "button"} ×
      Sprint status: #{@project.sprints.last.state.humanize}
    %table{class: "table table-hover", id: "no_drag", name: @project.id}
      %thead
        %tr
          %th Name
          %th Description
          %th Status
          %th Difficulty
      -@project.sprints.last.features.each do |feature|
        %tr{id: feature.id}
          %td= feature.name
          %td= feature.description
          %td
            %span{class: "label label-#{feature.set_status_label}"}
              = feature.state.humanize
          %td= feature.difficulty
          -#%td= link_to 'Show', [@project, feature], class: 'btn btn-small', type:'button'
          -if can? :manage, Feature
            %td= link_to 'Edit', edit_project_feature_path(@project, feature), class: 'btn btn-warning btn-small', type:'button'
            %td= link_to 'Delete', project_feature_path(@project, feature), class: 'btn btn-danger btn-small', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
            %td= link_to "#{feature.set_state_change_button}", url_for(controller: :features, action: :update, project_id: @project.id, id: feature.id, feature: { state_event: feature.set_state_transition }), class: "btn btn-small #{feature.set_disabled_button} tBTN", type:'button', method: :put
    -if can? :create, Feature
      = link_to 'New Feature', new_project_feature_path(@project), class: "btn #{@project.disable_new_feature}", type:'button'
      %br/
      %br/

app/views/features/_tab_navbar.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%ul.nav.nav-tabs#sprintTab
  -if @project.sprints.last
    %li.active
      %a{href: "#currentSprint"} Current Sprint
    -if @project.get_unassigned_features.count != 0
      %li
        %a{href: "#noSprint"} Unassigned
  %li
    %a{href: "#allFeatures"} All features
  -if @project.sprints.count > 1
    %li
      %a{href: "#pastSprints", id: "pastS"} Past Sprints

app/views/features/_tab_no_sprint.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
.tab-pane#noSprint
  %table{class: "table table-hover #{if can? :prioritize_feature, @project; @project.drag_available else "no_drag" end}", name: @project.id}
    %thead
      %tr
        %th Name
        %th Description
        %th Status
        %th Difficulty
    -@features.each do |feature|
      -if feature.sprint.nil?
        %tr{id: feature.id}
          %td= feature.name
          %td= feature.description
          %td
            %span{class: "label label-#{feature.set_status_label}"}
              = feature.state.humanize
          %td= feature.difficulty
          -if can? :manage, Feature
            %td= link_to 'Edit', edit_project_feature_path(@project, feature), class: 'btn btn-warning btn-small', type:'button'
            %td= link_to 'Delete', project_feature_path(@project, feature), class: 'btn btn-danger btn-small', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
            %td= link_to "#{feature.set_state_change_button}", url_for(controller: :features, action: :update, project_id: @project.id, id: feature.id, feature: { state_event: feature.set_state_transition }), class: "btn btn-small #{feature.set_disabled_button} tBTN", type:'button', method: :put

app/views/features/edit.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend
  Editing feature:
  = @feature.name

= render 'form'

= link_to 'Back', project_path(@feature.project), class: 'btn btn-success', type:'button'

app/views/features/index.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend
  = @project.name
  's current features

.alert.alert-success{style: "display: none;", id: "sorted"}
%table{class: "table table-hover", id: if can? :update, Project; @project.drag_available else "no_drag" end, name: @project.id}
  %thead
    %tr
      %th Name
      %th Description
      %th State
      %th Priority
      %th Difficulty
  - @features.each do |feature|
    %tr{id: feature.id}
      %td= feature.name
      %td= feature.description
      %td
        %span{class: "label label-#{feature.set_status_label}"}
          = feature.state.humanize
      %td= feature.priority
      %td= feature.difficulty
      %td= link_to 'Show', [@project, feature], class: 'btn btn-small', type:'button'
      -if can? :manage, Feature
        %td= link_to 'Edit', edit_project_feature_path(@project, feature), class: 'btn btn-warning btn-small', type:'button'
        %td= link_to 'Delete', project_feature_path(@project, feature), class: 'btn btn-danger btn-small', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to "#{feature.set_state_change_button}", url_for(controller: :features, action: :update, project_id: @project.id, id: feature.id, feature: { state_event: feature.set_state_transition }), class: "btn btn-small #{feature.set_disabled_button} tBTN", type:'button', method: :put
%br

-if can? :manage, Feature
  = link_to 'New Feature', new_project_feature_path(@project), class: 'btn btn-primary', type:'button'
= link_to 'Back', project_path(@project), class: 'btn btn-success', type:'button'

app/views/features/new.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend
  New feature for
  = @project.name

= render 'form'

= link_to 'Back', project_path(@project), class: 'btn btn-success', type:'button'

app/views/features/show.html.haml
-## Cotopaxi | Scrum Management Tool
-## Copyright (C) 2012  MHM-Systemhaus GmbH
-##
-## This program is free software: you can redistribute it and/or modify
-## it under the terms of the GNU General Public License as published by
-## the Free Software Foundation, either version 3 of the License, or
-## any later version.
-##
-## This program is distributed in the hope that it will be useful,
-## but WITHOUT ANY WARRANTY; without even the implied warranty of
-## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-## GNU General Public License for more details.
-## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
%legend
  = @feature.name
  for project:
  = @feature.project.name
%br
%h6 Description:
%p= @feature.description
%br
%table{class: "table table-hover"}
  %thead
    %tr
      %th Priority
      %th Difficulty
      %th Status
    %tr
      %td= @feature.priority
      %td= @feature.get_difficulty
      %td
        %span{class: "label label-#{@feature.set_status_label}"}
          = @feature.state.humanize


-if can? :manage, Feature
  = link_to 'Edit', edit_project_feature_path(@feature.project, @feature), class: 'btn btn-warning', id: "editF", type:'button'
  = link_to 'Delete', project_feature_path(@feature.project, @feature), class: 'btn btn-danger', type:'button', method: :delete, data: { confirm: 'Are you sure?' }
  = link_to "#{@feature.set_state_change_button}", url_for(controller: :features, action: :update, project_id: @feature.project_id, id: @feature.id, feature: { state_event: @feature.set_state_transition }), class: "btn #{@feature.set_disabled_button}", type:'button', method: :put
= link_to 'Back', project_path(@feature.project), class: 'btn btn-success', type:'button'